# Generated by Django 2.2.2 on 2019-06-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quizes',
            new_name='Quizzes',
        ),
    ]
