# Generated by Django 2.2.2 on 2019-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answers_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_pic',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_pic',
            field=models.TextField(default=''),
        ),
    ]
