# Generated by Django 2.2.2 on 2019-07-03 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizzes_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='last_use',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 18, 44, 33, 770791)),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='url_name',
            field=models.SlugField(unique=True),
        ),
    ]
