# Generated by Django 2.2.2 on 2019-07-03 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190703_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='last_use',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 19, 9, 4, 208867, tzinfo=utc)),
        ),
    ]
