# Generated by Django 2.2.2 on 2019-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190710_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprogress',
            name='last_seen',
            field=models.DateField(null=True),
        ),
    ]
