# Generated by Django 2.2.2 on 2019-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20190711_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
