# Generated by Django 2.2.2 on 2019-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20190717_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_correct',
            field=models.BooleanField(default=False),
        ),
    ]
